name: Card Monitor
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install requests beautifulsoup4
      - name: Run script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python ./main.py
      - name: Push history
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add history.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update history" && git push)
